apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
    - name: 'tcp'
      port: 3006
      protocol: TCP
      targetPort: 3006
  selector:
    app: gateway
  type: ClusterIP
