apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments-http
spec:
  ports:
    - name: 'http'
      port: 3005
      protocol: TCP
      targetPort: 3005
  selector:
    app: payments
  type: NodePort
